fastly.settings:
  type: config_object
  label: 'Fastly Settings'
  mapping:
    api_key:
      type: string
      label: 'Fastly API key'
    cache_tag_hash_length:
      type: integer
      label: 'Cache tag hash length'
    image_optimization:
      type: boolean
      label: 'Enable image optimization'
    jpeg_quality:
      type: integer
      label: 'Default JPEG quality'
    jpeg_type:
      type: string
      label: 'Default JPEG format'
    site_id:
      type: string
      label: 'Fastly Site ID'
    service_id:
      type: string
      label: 'Fastly Service ID'
    purge_logging:
      type: boolean
      label: 'Fastly purge logging'
    purge_method:
      type: string
      label: 'Fastly Purge Method'
    resize_filter:
      type: string
      label: 'Resize filter'
    stale_while_revalidate:
       type: boolean
       label: 'Fastly stale while revalidate'
    stale_while_revalidate_value:
      type: integer
      label: 'Fastly stale while revalidation value'
    stale_if_error:
      type: boolean
      label: 'Fastly stale if error'
    stale_if_error_value:
      type: integer
      label: 'Fastly stale if error value'
    upscale:
      type: boolean
      label: 'Allow upscaling'
    webhook_notifications:
      type: array
      label: 'Webhook notifications'
    webhook_enabled:
      type: boolean
      label: 'Webhook enabled'
    webhook_url:
      type: string
      label: 'Webhook URL'
    webp:
      type: boolean
      label: 'Auto WebP'
    webp_quality:
      type: integer
      label: 'Default WebP (lossy) quality'
